markdown_extensions:
  - meta
  - toc:
      permalink: true
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - js/tabsync.js

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    primary: white
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - toc.integrate

site_name: Krux - Open-source hardware signer for Bitcoin
site_description: Krux is an open-source DIY hardware signer for Bitcoin that can sign for multisignature and single-key wallets. It is a low-cost airgapped device built from off-the-shelf parts that communicates with wallet software via QR codes and wipes its memory after every session.
site_url: https://selfcustody.github.io/krux/
repo_url: https://github.com/selfcustody/krux
edit_uri: edit/main/docs
docs_dir: docs
site_dir: public
extra:
  social:
    - icon: material/chat
      link: https://matrix.to/#/#krux:matrix.org
      name: Join our Matrix server
    - icon: fontawesome/brands/github
      link: https://github.com/selfcustody/krux

nav:
  - Home: index.en.md
  - Getting Started:
    - About: getting-started/index.en.md
    - Installing: getting-started/installing.en.md
    - Generating a Mnemonic: getting-started/generating-a-mnemonic.en.md
    - Loading a Mnemonic: getting-started/loading-a-mnemonic.md
    - Navigating the Main Menu: getting-started/navigating-the-main-menu.md
    - Using a Single-key Wallet: getting-started/using-a-single-key-wallet.md
    - Using a Multisig Wallet: getting-started/using-a-multisig-wallet.md
    - Printing: getting-started/printing.md
    - Settings: getting-started/settings.md
  - Part List:
    - parts.en.md
    - parts.pt.md
  - FAQ: faq.md
  - Support the Project:
    - support.en.md
    - support.pt.md


plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        es: 
          name: Español
          site_name: Krux - Hardware de firma de código abierto para Bitcoin
        se: 
          name: Esperanto
          site_name: Krux - Malfermfonta Subskribo-Aparataro por Bitcoin
        pt: 
          name: Português
          site_name: Krux - Hardware de assinatura de código-aberto para Bitcoin
      nav_translations:
        es:
          Home: Principal
          Getting Started: Empezando
          Part List: Lista de piezas
          FAQ: Preguntas frecuentes
          Support the Project: Apoyar el proyecto
          About: Sobre
          Installing: Instalando
          Generating a Mnemonic: Generando un mnemotécnico
          Loading a Mnemonic: Cargando un mnemotécnico
          Navigating the Main Menu: Navegación por el menú principal
          Using a Single-key Wallet: Usando una billetera de una sola tecla
          Using a Multisig Wallet: Uso de una billetera de firmas múltiples
          Printing: Impresión
          Settings: Ajustes
        se:
          Home: Hejmen
          Getting Started: Komencante
          Part List: Parto listo
          FAQ: Oftaj demandoj
          Support the Project: Subtenu la projekton
          About: Pri
          Installing: Instalante
          Generating a Mnemonic: Generante Mnemonikon
          Loading a Mnemonic: Ŝargante Mnemonikon
          Navigating the Main Menu: Navigante la Ĉefan Menuon
          Using a Single-key Wallet: Uzante la Unuŝlosan Monujon
          Using a Multisig Wallet: Uzante la Multisig Monujon
          Printing: Presado
          Settings: Agordoj
        pt:
          Home: Principal
          Getting Started: Começando
          Part List: Lista de peças
          FAQ: Perguntas frequentes
          Support the Project: Apoie o Projeto
          About: Sobre
          Installing: Instalando
          Generating a Mnemonic: Gerando um Mnemônico
          Loading a Mnemonic: Carregando um Mnemônico
          Navigating the Main Menu: Navegando no Menu principal
          Using a Single-key Wallet: Usando uma carteira de chave-única
          Using a Multisig Wallet: Usando uma carteira Multiassinatura
          Printing: Imprimindo
          Settings: Configurações

