# The MIT License (MIT)

# Copyright (c) 2021 Tom J. Sun

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

[tool.poetry]
name = "krux"
version = "22.03.0"
description = "Open-source, airgapped bitcoin hardware signer for the M5StickV"
authors = ["Jeff S <jeffreesun@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.1"
embit = { path = "./vendor/embit/", develop = true }
ur = { path = "./vendor/foundation-ur-py/", develop = true }
urtypes = { path = "./vendor/urtypes/", develop = true }
mkdocs-static-i18n = {version = "^0.46", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mkdocs = "^1.2.3"
pylint = "^2.12.2"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
PyQRCode = {version = "^1.2.1", optional = true}
pygame = {version = "^2.1.2", optional = true}
opencv-python = {version = "^4.5.5", optional = true}
numpy = {version = "^1.22.3", optional = true}
Pillow = {version = "^9.0.1", optional = true}
pyzbar = {version = "^0.1.9", optional = true}

[tool.poetry.extras]
docs = ["mkdocs-static-i18n"]